print("Time to solve some Mensuration Problems! We shall now find the area of a Rectangle with given Length and Breadth!")
print("Remember, the length is always greater than breadth!")
l = float(input("Enter the length of the Rectangle: "))
b = float(input("Enter the breadth of the Rectangle: "))
area = round((l*b),3)
print(f"The area of the Rectangle is {area} square units.")